# Meta
description: A minimal hexo theme.
keywords: hexo,theme,typescript,otakism,otaku
site_desc: "정리좀 하면서 살자"

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: thinking
  slug: thinking
  url: /thinking
- name: Sites
  slug: sites
  url: /sites
- name: Archives
  slug: archives
  url: /archives

# Search
search:
  enable: false
  service: google # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics: UA-96857641-1
favicon: /favicon.png
author_url: http://rakugaki.me

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: mailto:sangpire@gmail.com
- slug: github
  url: https://github.com/sangpire
- slug: twitter
  url: https://twitter.com/sangpire
- slug: rss
  url: /atom.xml
- slug: google
  url: https://plus.google.com/+sangpire
- slug: facebook
  url: https://www.facebook.com/sangpire
